#!/bin/sh

# Automatically added by dh_installinit
if [ -x "/etc/init.d/isconf" ]; then
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d isconf stop || exit $?
	else
		/etc/init.d/isconf stop || exit $?
	fi
fi
# End automatically added section

# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p isconf 
else
	dpkg -L isconf | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section
