#!/bin/sh
# postinst script for kumir

set -e

case "$1" in
    configure)
      update-mime-database /usr/share/mime > /dev/null
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
