Document: python-xml
Title: Debian python-xml Manual
Author: <insert document author here>
Abstract: This manual describes what python-xml is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-xml/python-xml.sgml.gz

Format: postscript
Files: /usr/share/doc/python-xml/python-xml.ps.gz

Format: text
Files: /usr/share/doc/python-xml/python-xml.text.gz

Format: HTML
Index: /usr/share/doc/python-xml/html/index.html
Files: /usr/share/doc/python-xml/html/*.html
